apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: counterd-dep2
  name: counterd-dep2
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: counterd-dep2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: counterd-dep2
    spec:
      containers:
      - image: localhost:5000/k8s_workshop/counterd:1
        imagePullPolicy: IfNotPresent
        name: counterd
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
